spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  application:
    name: starter
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
logging:
  level:
    org.springframework: ERROR
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR
    org.mapstruct: ERROR
security:
  configuration:
    jwt:
      secret: "MuySeguraLlaveDe32CaracteresMinimo!@#1234"
      expiration: 3600
      issuer: SmartJob
      audience: SmartJobAudience
user:
  password:
    regex: "^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d]{8,}$"
  email:
    regex: "^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,6}$"
server:
  port: 8081